# Generated by Django 2.2.12 on 2020-06-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSection',
            fields=[
                ('section_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
